name: Zip Release

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release Name"
        required: true
      tag_name:
        description: "Tag Name"
        required: true
      release_description:
        description: "Release Description"
        required: true

jobs:
  zip-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Zip All PDFs
        run: find . -type f \( -iname "*.pdf" \) -exec zip -j sheets.zip {} \;

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          body: ${{ github.event.inputs.release_description }}
          files: sheets.zip
          draft: false
          prerelease: false
